# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fc19a9a5-7f88-432d-bd39-40a0b2a6e313";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fc19a9a5-7f88-432d-bd39-40a0b2a6e313".device = "/dev/disk/by-uuid/fc19a9a5-7f88-432d-bd39-40a0b2a6e313";
  boot.initrd.luks.devices."luks-30df3ce3-5966-45c7-bc5d-288320d1cf07".device = "/dev/disk/by-uuid/30df3ce3-5966-45c7-bc5d-288320d1cf07";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/76F5-AFD4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-30df3ce3-5966-45c7-bc5d-288320d1cf07"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
