#!/usr/bin/env bash

open_nvim() {
  cd ~/.config/nvim/lua/myconfig
  nvim init.lua
}

ask_yes_no() {
  local prompt="$1"
  while true; do
    read -r -p "$prompt [Y/n]: " response
    case "$response" in
      [Yy]* | "" ) return 0;;  # Yes or default (Enter)
      [Nn]* ) return 1;;       # No
      * ) echo "Please answer yes or no.";;
    esac
  done
}

BAK_DIR=~/.config/nvim.bak/
if [ -d $BAK_DIR ]; then
  echo "Still editing neovim config! ($BAK_DIR detected)"
  if ask_yes_no "Do you want to open neovim?"; then
    open_nvim
  fi
  exit 0
fi

replace_symlink() {
  local link="$1"
  target=$(readlink "$link")
  
  if [ -f "$target" ]; then
    cp --remove-destination "$target" "$link"
    chmod +w "$link" 
    echo "Replaced symlink $link with the target file."
  else
    echo "Target file $target does not exist or is not a regular file for symlink $link."
  fi
}

# Function to replace symlinks with actual files
replace_symlinks() {
  local dir="$1"
  find "$dir" -type l | while read -r link; do
    replace_symlink $link
  done
}

cp -r ~/.config/nvim $BAK_DIR
replace_symlink ~/.config/nvim/lazy-lock.json
replace_symlinks ~/.config/nvim/lua/myconfig

open_nvim
